# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container:
      image: ubuntu:latest
    strategy:
      matrix:
        dotnet-version: [8.0.12, 8.0.13]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Install dependencies
        run: apt-get update && apt-get install -y curl ca-certificates
        
      - name: Download and install .NET
        run: |
          curl -fsSL https://dotnet.microsoft.com/en-us/download/dotnet/scripts/v1/dotnet-install.sh | bash /dev/stdin --version ${{ matrix.dotnet-version }} --install-dir /usr/share/dotnet
          echo "export PATH=/usr/share/dotnet:\$PATH" >> $GITHUB_ENV

      - name: Verify .NET installation
        run: dotnet --info
        
      # - name: .NET build
      #   run: dotnet build
